### ISSUE TITLE
luasq-mysql cannot run

### ISSUE THREAD

**Issue by soforo** [lunarmodules/luasql#122]
Hi, I cannot require luasql.mysql module and raise follow error. I tested luasql-mysql 2.5.0 and luasql-mysql 2.3.5 and luasql-mysql 2.1.1. Mysql Server version: 5.7.30 MySQL Community Server (GPL)。What's wrong with this？

With the yum installed lua:

> Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
> > require 'luasql.mysql'
> error loading module 'luasql.mysql' from file '/usr/lib64/lua/5.1/luasql/mysql.so':
> 	/usr/lib64/lua/5.1/luasql/mysql.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE
> stack traceback:
> 	[C]: ?
> 	[C]: in function 'require'
> 	stdin:1: in main chunk
> 	[C]: ?

With  installed lua， still appears this error
> [root@localhost home]# lua
> Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> > require 'luasql.mysql'
> error loading module 'luasql.mysql' from file '/usr/local/lib/lua/5.1/luasql/mysql.so':
> 	/usr/local/lib/lua/5.1/luasql/mysql.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE
> stack traceback:
> 	[C]: ?
> 	[C]: in function 'require'
> 	stdin:1: in main chunk
> 	[C]: ?

**Comment by tomasguisasola** [comment]
The message says the file could not be found.  This could have happened because of different causes.

1. Since Lua release does not include LuaSQL, you have to install it.  It should require you to install a developer's library also.

2. If you have the driver installed somewhere, your `package.cpath` should point to that path.  In case you used LuaRocks, you just have to load `luarocks.require` or `luarocks.loader` to update your cpath.
